# Generated by Django 5.0.7 on 2024-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('subscription_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('trial', 'Trial')], default='inactive', max_length=10, null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_trial_used', models.BooleanField(default=False)),
                ('is_auto_renewal', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('educational_status', models.IntegerField(blank=True, choices=[(1, 'Estudiante MIR para una primera especialidad'), (2, 'Estudiante MIR que ya tiene alguna especialidad'), (3, 'Estudiante de Medicina'), (4, 'Ninguna de las anteriores')], null=True)),
                ('desired_specialty', models.IntegerField(blank=True, choices=[(1, 'Alergología'), (2, 'Análisis Clínicos'), (3, 'Anatomía Patológica'), (4, 'Anestesiología y Reanimación'), (5, 'Angiología y Cirugía Vascular'), (6, 'Aparato Digestivo'), (7, 'Bioquímica Clínica'), (8, 'Cardiología'), (9, 'Cirugía Cardiovascular'), (10, 'Cirugía Gral. y del A.Digestivo'), (11, 'Cirugía Oral y Maxilofacial'), (12, 'Cirugía Ortopédica y Traumatología'), (13, 'Cirugía Pediátrica'), (14, 'Cirugía Plástica Estética y Reparadora'), (15, 'Cirugía Torácica'), (16, 'Dermatología Médico-Quirúrgica y V.'), (17, 'Endocrinología y Nutrición'), (18, 'Ginecología'), (19, 'Geriatría'), (20, 'Hematología y Hemoterapia'), (21, 'Inmunología'), (22, 'Medicina del Trabajo'), (23, 'Medicina Familiar y Comunitaria'), (24, 'Medicina Física y Rehabilitación'), (25, 'Medicina Intensiva'), (26, 'Medicina Interna'), (27, 'Medicina Legal y Forense'), (28, 'Medicina Nuclear'), (29, 'Medicina Preventiva y Salud Pública'), (30, 'Microbiología y Parasitología'), (31, 'Nefrología'), (32, 'Neumología'), (33, 'Neurocirugía'), (34, 'Neurofisiología Clínica'), (35, 'Neurología'), (36, 'Obstetricia y Ginecología'), (37, 'Oftalmología'), (38, 'Oncología Médica'), (39, 'Oncología Radioterápica'), (40, 'Otorrinolaringología'), (41, 'Pediatría'), (42, 'Psiquiatría'), (43, 'Radiodiagnóstico'), (44, 'Reumatología'), (45, 'Urgencias y Emergencias'), (46, 'Urología')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
