# Generated by Django 5.0.7 on 2024-07-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
    ]
