# Generated by Django 5.0.7 on 2024-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_auto_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
