# Generated by Django 5.0.7 on 2024-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_email_verified_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('trial', 'Trial')], default='inactive'),
        ),
    ]
