# Generated by Django 5.0.7 on 2024-08-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('trial', 'Trial')], default='inactive', max_length=20),
        ),
    ]
