# Generated by Django 5.0.7 on 2024-08-11 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_edited_at_thread_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='edited_by',
        ),
    ]
