# Generated by Django 5.0.7 on 2024-08-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_thread_edited_at_remove_thread_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='title',
            field=models.CharField(default='default title', max_length=255),
            preserve_default=False,
        ),
    ]
